"""Telegram alerts. Silently disabled when no token is configured."""
import logging
import httpx

import config

log = logging.getLogger("notify")
_seen = set()


def enabled() -> bool:
    return bool(config.TELEGRAM_BOT_TOKEN and config.TELEGRAM_CHAT_ID)


def send(text: str, dedupe_key: str = None) -> bool:
    if not enabled():
        return False
    if dedupe_key:
        if dedupe_key in _seen:
            return False
        _seen.add(dedupe_key)
    url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage"
    try:
        httpx.post(url, timeout=10, json={
            "chat_id": config.TELEGRAM_CHAT_ID,
            "text": text,
            "parse_mode": "HTML",
            "disable_web_page_preview": True,
        })
        return True
    except Exception as exc:                           # noqa: BLE001
        log.warning("telegram send failed: %s", exc)
        return False


def call_alert(call: dict) -> bool:
    body = (
        f"<b>{call['tier']}  {call['symbol']}</b>\n"
        f"Score {call['score']}\n"
        f"Entry {call['entry']}  SL {call['sl']}\n"
        f"T1 {call['t1']}  T2 {call['t2']}  T3 {call['t3']}\n"
        f"Why: {call.get('why', '')}\n\n"
        f"<i>Generated by a scanner. Not advice. Verify before acting.</i>"
    )
    return send(body, dedupe_key=f"call:{call['id']}")


def status_alert(call: dict, status: str) -> bool:
    return send(
        f"<b>{call['symbol']}</b> -> {status}\n"
        f"LTP {call['ltp']}  best seen {call['max_seen']}",
        dedupe_key=f"status:{call['id']}:{status}",
    )
